package generate

import (
	"fmt"
	"path/filepath"
	"strings"

	"github.com/ishuar/tfskel/internal/templates"
)

// Run executes the generation process with the provided generation parameters
func (g *Generator) Run(env, region, appDir string) error {
	if err := g.initRenderer(); err != nil {
		return err
	}

	// Create directory structure: envs/<env>/<region>/<app>
	appPath := filepath.Join("envs", env, region, appDir)

	// Check if directory already exists
	dirExists := g.fs.DirExists(appPath)

	if err := g.fs.MkdirAll(appPath, 0755); err != nil {
		return fmt.Errorf("failed to create directory structure: %w", err)
	}

	// Show appropriate message based on whether directory was created or already existed
	if dirExists {
		g.log.Infof("Directory %s already exists", appPath)
	} else {
		g.log.Successf("Created directory structure: %s", appPath)
	}

	// Generate files from templates
	if err := g.generateFiles(appPath, env, region, appDir); err != nil {
		return err
	}

	// Display success message
	absPath, err := filepath.Abs(appPath)
	if err != nil {
		absPath = appPath
	}
	g.log.Successf("Created directory: %s", absPath)

	return nil
}

// RunWorkflows generates per-environment GitHub workflow files.
// It processes only github/*.tmpl files (dynamic, env-specific workflows).
// Static reusable workflows are generated by the init command instead.
func (g *Generator) RunWorkflows(env string) error {
	// Check if workflows are enabled
	if g.config.Workflows == nil || !g.config.Workflows.Create {
		g.log.Info("Workflow generation is disabled (workflows.create: false in config)")
		return nil
	}

	if err := g.initRenderer(); err != nil {
		return err
	}

	// Get account ID for the environment
	accountID, err := g.config.GetAccountID(env)
	if err != nil {
		return err
	}

	// Build minimal template data (env + accountID are sufficient for workflow templates)
	data := &templates.Data{
		Env:       env,
		AccountID: accountID,
	}

	// Build AWS role ARN
	awsRoleArn, err := g.buildAWSRoleArn(data)
	if err != nil {
		return fmt.Errorf("failed to build AWS role ARN: %w", err)
	}
	data.AWSRoleArn = awsRoleArn

	g.log.Infof("Generating workflow files for environment: %s", env)

	// Process only github .tmpl files
	for _, tmplPath := range g.renderer.GetTemplateNames() {
		normalizedPath := filepath.ToSlash(tmplPath)
		if !strings.HasPrefix(normalizedPath, categoryGithub+"/") || !strings.HasSuffix(tmplPath, ".tmpl") {
			continue // static files go via init
		}

		templateData := *data
		if err := g.enrichTemplateDataForWorkflow(tmplPath, &templateData); err != nil {
			return err
		}

		outputPath, valid := g.determineOutputPath(tmplPath, "", &templateData)
		if !valid {
			g.log.Debugf("Skipping template with invalid path format: %s", tmplPath)
			continue
		}

		if g.fs.FileExists(outputPath) {
			if g.upgrade {
				if err := g.upgradeFileIfEligible(tmplPath, outputPath, &templateData); err != nil {
					return err
				}
			} else {
				g.log.Infof("%s already exists, skipping", outputPath)
			}
			continue
		}

		if err := g.writeTemplateFile(tmplPath, outputPath, outputPath, &templateData); err != nil {
			return err
		}
	}

	return nil
}

// generateFiles iterates over all templates and generates files
// Custom templates override default templates with the same name
// Root-level templates are placed at project root, app-level templates go in the app directory
func (g *Generator) generateFiles(appPath, env, region, appDir string) error {
	g.log.Infof("Generating files in %s...", appPath)

	// Prepare template data
	data, err := g.prepareTemplateData(env, region, appDir)
	if err != nil {
		return err
	}

	// Check and update backend.tf if needed
	if err := g.updateBackendIfNeeded(appPath, data); err != nil {
		return err
	}

	// Check and update versions.tf if needed
	if err := g.updateVersionsIfNeeded(appPath, data); err != nil {
		return err
	}

	// Process all templates
	return g.processTemplates(appPath, data)
}

// processTemplates iterates through templates and generates files
func (g *Generator) processTemplates(appPath string, data *templates.Data) error {
	allTemplates := g.renderer.GetTemplateNames()

	for _, tmplPath := range allTemplates {
		if err := g.processTemplate(tmplPath, appPath, data); err != nil {
			return err
		}
	}

	return nil
}

// processTemplate handles generation of a single template file
func (g *Generator) processTemplate(tmplPath, appPath string, data *templates.Data) error {
	// Check if template should be skipped
	shouldSkip, reason := g.shouldSkipTemplate(tmplPath)
	if shouldSkip {
		g.log.Debugf("Skipping %s: %s", tmplPath, reason)
		return nil
	}

	// Create a copy of data for this template
	templateData := *data

	// Enrich data for workflow templates
	if err := g.enrichTemplateDataForWorkflow(tmplPath, &templateData); err != nil {
		g.log.Errorf("Failed to enrich template data for %s: %v", tmplPath, err)
		return err
	}

	// Determine output path
	outputPath, valid := g.determineOutputPath(tmplPath, appPath, &templateData)
	if !valid {
		g.log.Debugf("Skipping template with invalid path format: %s", tmplPath)
		return nil
	}

	// Handle existing files
	if g.fs.FileExists(outputPath) {
		if g.upgrade {
			return g.upgradeFileIfEligible(tmplPath, outputPath, &templateData)
		}
		g.log.Infof("%s already exists, skipping", outputPath)
		return nil
	}

	// Create output directory and write file
	return g.writeTemplateFile(tmplPath, outputPath, outputPath, &templateData)
}
